export type Biomarker = {
    slug: string;
    name: string;
    en: string;
    color: string;
    illustration: string;
    category: string;
    tagline: string;
    role: string;
    standardRange: string;
    optimalRange?: string;
    highSigns: string;
    lowSigns: string;
    relatedNutrients: string[];
    relatedGenes: string[];
    tips: string[];
};

export const biomarkers: Biomarker[] = [

    // ===== 血球・貧血 =====
    {
        slug: 'rbc',
        name: '赤血球数',
        en: 'RBC',
        color: '#FBE2E2',
        illustration: '/images/for-you-recovery.png',
        category: '血球・貧血',
        tagline: '全身へ酸素を運ぶ赤血球の「数」',
        role: '赤血球は、ヘモグロビンを使って肺から全身の細胞へ酸素を届ける細胞です。ミトコンドリアがエネルギー(ATP)を作るには酸素が不可欠なため、赤血球の数はエネルギー産生の基盤そのものです。数だけでなく、後続のHb・MCV・フェリチンと合わせて「貧血の種類」を見極めることが重要です。',
        standardRange: '男性 430〜570万/μL、女性 380〜500万/μL',
        optimalRange: '男性 480〜540万/μL、女性 420〜480万/μL',
        highSigns: '多血症（脱水・喫煙・高地・骨髄疾患）',
        lowSigns: '貧血（鉄不足・B12/葉酸不足・慢性疾患）',
        relatedNutrients: ['iron', 'b12', 'folate', 'vitamin-c', 'b6'],
        relatedGenes: ['mthfr'],
        tips: ['Hb・MCV・フェリチンとセットで判断', '低い場合は貧血の「型」を確認', 'タンパク質・鉄・B12を見直す'],
    },
    {
        slug: 'hemoglobin',
        name: 'ヘモグロビン',
        en: 'HEMOGLOBIN (Hb)',
        color: '#FBE2E2',
        illustration: '/images/for-you-recovery.png',
        category: '血球・貧血',
        tagline: '酸素を運ぶタンパク質の「量」',
        role: 'ヘモグロビンは赤血球の中にある鉄含有タンパク質で、酸素と結合して全身へ運びます。貧血診断の中心となる指標で、低値は酸素運搬能の低下を意味し、疲労・息切れ・集中力低下に直結します。Hb単独より、MCV・フェリチンと組み合わせて貧血の原因を特定するのが重要です。',
        standardRange: '男性 13.5〜17.5 g/dL、女性 11.5〜15.0 g/dL',
        optimalRange: '男性 14.5〜16.5 g/dL、女性 13.0〜14.5 g/dL',
        highSigns: '多血症・脱水・喫煙',
        lowSigns: '貧血（疲労・息切れ・冷え・集中力低下）',
        relatedNutrients: ['iron', 'b12', 'folate', 'protein', 'b6'],
        relatedGenes: ['mthfr'],
        tips: ['女性は13 g/dLを下回ったら要注意', 'MCVで貧血の種類（小球性・大球性）を判別', '鉄・B12・葉酸を確認'],
    },
    {
        slug: 'hematocrit',
        name: 'ヘマトクリット',
        en: 'HEMATOCRIT (Ht)',
        color: '#FBE2E2',
        illustration: '/images/for-you-recovery.png',
        category: '血球・貧血',
        tagline: '血液中の赤血球が占める「割合」',
        role: 'ヘマトクリットは、血液全体に占める赤血球の体積割合を示す指標です。Hbと並行して動くことが多く、貧血の程度を確認するために使われます。脱水では見かけ上上昇し、水分摂取が少ない人は過剰評価になりやすい点に注意が必要です。',
        standardRange: '男性 40〜52%、女性 36〜45%',
        optimalRange: '男性 42〜48%、女性 38〜43%',
        highSigns: '脱水・多血症・喫煙',
        lowSigns: '貧血・過剰な水分摂取',
        relatedNutrients: ['iron', 'b12', 'folate'],
        relatedGenes: [],
        tips: ['水分補給の状態で変動する', 'HbやRBCと合わせて読む', '脱水が疑われる場合は補正が必要'],
    },
    {
        slug: 'mcv',
        name: 'MCV（平均赤血球容積）',
        en: 'MCV',
        color: '#FBE2E2',
        illustration: '/images/for-you-science.png',
        category: '血球・貧血',
        tagline: '赤血球の「大きさ」で貧血の原因を見分ける',
        role: 'MCVは赤血球1個の平均的な大きさを示す指標で、貧血の「型」を分類する重要な手がかりです。小さい（小球性）場合は鉄欠乏・慢性疾患、大きい（大球性）場合はビタミンB12や葉酸の不足を疑います。Hbが正常でもMCVが変化している場合は「潜在的な不足」のサインになります。',
        standardRange: '80〜100 fL',
        optimalRange: '85〜95 fL',
        highSigns: 'ビタミンB12欠乏・葉酸欠乏・アルコール過多（大球性貧血）',
        lowSigns: '鉄欠乏・慢性炎症・サラセミア（小球性貧血）',
        relatedNutrients: ['iron', 'b12', 'folate'],
        relatedGenes: ['mthfr'],
        tips: ['MCVで「どの栄養が足りないか」の見当がつく', 'B12・葉酸不足はHbが正常でもMCVが上がる', '鉄不足は小さくなる'],
    },
    {
        slug: 'mch',
        name: 'MCH（平均赤血球ヘモグロビン量）',
        en: 'MCH',
        color: '#FBE2E2',
        illustration: '/images/for-you-science.png',
        category: '血球・貧血',
        tagline: '赤血球1個に含まれるヘモグロビンの「重さ」',
        role: 'MCHは赤血球1個に含まれるヘモグロビンの平均量を示します。MCVとほぼ連動して動くため、MCVと合わせて貧血のタイプを確認する補助指標として使われます。低値は鉄欠乏、高値はB12・葉酸不足を示唆することが多いです。',
        standardRange: '27〜34 pg',
        optimalRange: '28〜32 pg',
        highSigns: 'B12・葉酸欠乏（MCVと連動）',
        lowSigns: '鉄欠乏・小球性貧血',
        relatedNutrients: ['iron', 'b12', 'folate'],
        relatedGenes: ['mthfr'],
        tips: ['MCVとセットで読む', '単独で判断するより他の指標との組み合わせを', '貧血の原因絞り込みに役立つ'],
    },
    {
        slug: 'wbc',
        name: '白血球数',
        en: 'WBC',
        color: '#FBE2E2',
        illustration: '/images/for-you-wellness.png',
        category: '血球・貧血',
        tagline: '免疫の最前線、感染・炎症のバロメーター',
        role: '白血球は免疫の主力部隊で、細菌・ウイルス・異物を排除する役割を担います。感染症・炎症・アレルギー・ストレスなど様々な要因で増減するため、総数だけでなく分画（好中球・リンパ球・単球など）の割合も重要です。慢性的な低値は免疫力の低下、高値は慢性炎症のサインになります。',
        standardRange: '3,500〜9,000 /μL',
        optimalRange: '4,500〜7,000 /μL',
        highSigns: '感染症・慢性炎症・ストレス・喫煙',
        lowSigns: '免疫抑制・栄養不足・過労',
        relatedNutrients: ['vitamin-c', 'vitamin-d', 'zinc', 'protein'],
        relatedGenes: [],
        tips: ['分画（好中球比率など）も合わせて確認', '慢性的に8000超は炎症を疑う', '亜鉛・ビタミンC・Dで免疫を支える'],
    },
    {
        slug: 'platelets',
        name: '血小板数',
        en: 'PLATELETS',
        color: '#FBE2E2',
        illustration: '/images/for-you-wellness.png',
        category: '血球・貧血',
        tagline: '出血を止める「止血」の担い手',
        role: '血小板は出血した際に集まって血栓を作り、出血を止める役割を担う細胞片です。低値は出血リスク上昇、高値は血栓リスクにつながります。慢性炎症や鉄欠乏で反応的に増加することもあります。サプリや食事との関係では、魚油（オメガ3）の多量摂取で凝集が弱まる場合があります。',
        standardRange: '15〜35万/μL',
        optimalRange: '18〜30万/μL',
        highSigns: '炎症・鉄欠乏・血栓リスク',
        lowSigns: '出血リスク・免疫疾患・薬剤影響',
        relatedNutrients: ['omega3', 'vitamin-k2'],
        relatedGenes: [],
        tips: ['10万以下は要精査', 'オメガ3大量摂取は凝集に影響することがある', '定期的なモニタリングが重要'],
    },
    {
        slug: 'reticulocytes',
        name: '網状赤血球',
        en: 'RETICULOCYTES',
        color: '#FBE2E2',
        illustration: '/images/for-you-science.png',
        category: '血球・貧血',
        tagline: '骨髄が赤血球を「今どのくらい作っているか」',
        role: '網状赤血球は骨髄から出たばかりの若い赤血球で、赤血球産生の活動レベルを示します。貧血の際にこの値が高ければ骨髄が頑張って補おうとしている（反応性貧血）、低ければ産生そのものが落ちていることを示します。鉄欠乏治療の効果確認や、B12補充後の反応を見るのにも使われます。',
        standardRange: '0.5〜2.0%（成人）',
        optimalRange: '1.0〜2.0%',
        highSigns: '溶血性貧血・出血後の回復期',
        lowSigns: '鉄・B12・葉酸不足・骨髄機能低下',
        relatedNutrients: ['iron', 'b12', 'folate'],
        relatedGenes: ['mthfr'],
        tips: ['貧血の回復確認に有用', '治療後の経過観察に追う', '低値のまま続く場合は骨髄機能を確認'],
    },

    // ===== 鉄代謝 =====
    {
        slug: 'ferritin',
        name: 'フェリチン',
        en: 'FERRITIN',
        color: '#FCE3D4',
        illustration: '/images/for-you-recovery.png',
        category: '鉄代謝',
        tagline: '貯蔵鉄の「残量」を示す最重要指標',
        role: 'フェリチンは体内の鉄を貯蔵するタンパク質で、鉄の「貯金残高」を示します。ヘモグロビンが正常でもフェリチンが低い「潜在性鉄欠乏」は見逃されやすく、疲労・冷え・抜け毛・気分の落ち込みの原因になります。また炎症があると見かけ上高くなるため、CRPとセットで判断することが重要です。',
        standardRange: '男性 13〜280 ng/mL、女性 5〜157 ng/mL',
        optimalRange: '男性 60〜150 ng/mL、女性 40〜100 ng/mL',
        highSigns: '炎症・肝疾患・ヘモクロマトーシス（ただし炎症で偽高値も）',
        lowSigns: '鉄欠乏（疲労・冷え・抜け毛・気分の落ち込み）',
        relatedNutrients: ['iron', 'vitamin-c', 'protein'],
        relatedGenes: [],
        tips: ['基準値内でも30以下は機能的鉄欠乏', 'CRPが高いと炎症でフェリチンは偽高値になる', '月経のある女性は特に重要'],
    },
    {
        slug: 'serum-iron',
        name: '血清鉄',
        en: 'SERUM IRON',
        color: '#FCE3D4',
        illustration: '/images/for-you-recovery.png',
        category: '鉄代謝',
        tagline: '血液中を「今」流れている鉄の量',
        role: '血清鉄は血液中でトランスフェリンと結合して運ばれている鉄の量です。フェリチンより変動が大きく、食事・日内変動・炎症の影響を受けやすいため、単独での判断は難しい指標です。フェリチン・TIBC・トランスフェリン飽和度と合わせて「鉄の状態を立体的に把握する」のが正確です。',
        standardRange: '男性 60〜200 μg/dL、女性 50〜170 μg/dL',
        optimalRange: '男性 80〜160 μg/dL、女性 70〜140 μg/dL',
        highSigns: 'ヘモクロマトーシス・肝疾患・過剰摂取',
        lowSigns: '鉄欠乏・慢性疾患貧血',
        relatedNutrients: ['iron', 'vitamin-c', 'copper'],
        relatedGenes: [],
        tips: ['食後や炎症で変動大、単独判断は避ける', 'フェリチン・TIBCとセットで', '朝食前空腹時に測るのが基本'],
    },
    {
        slug: 'tibc',
        name: 'TIBC（総鉄結合能）',
        en: 'TIBC',
        color: '#FCE3D4',
        illustration: '/images/for-you-science.png',
        category: '鉄代謝',
        tagline: 'トランスフェリンが鉄を「あとどれだけ運べるか」',
        role: 'TIBCは、鉄を運ぶタンパク質「トランスフェリン」が最大どれだけの鉄を運べるかを示す指標です。鉄が不足するとトランスフェリンが増え（もっと鉄を運ぼうとする）、TIBCが上昇します。逆に炎症状態やタンパク質不足ではTIBCが低下します。血清鉄との比率がトランスフェリン飽和度になります。',
        standardRange: '250〜450 μg/dL',
        optimalRange: '280〜380 μg/dL',
        highSigns: '鉄欠乏（運搬能力を増やそうとしている）',
        lowSigns: '慢性疾患・炎症・タンパク質不足・ヘモクロマトーシス',
        relatedNutrients: ['iron', 'protein'],
        relatedGenes: [],
        tips: ['血清鉄÷TIBC×100=トランスフェリン飽和度', '鉄欠乏ではTIBC↑・血清鉄↓の組み合わせ', 'タンパク質不足で低くなる点に注意'],
    },
    {
        slug: 'transferrin-saturation',
        name: 'トランスフェリン飽和度',
        en: 'TRANSFERRIN SATURATION',
        color: '#FCE3D4',
        illustration: '/images/for-you-science.png',
        category: '鉄代謝',
        tagline: '鉄を運ぶトランスフェリンが「今どれだけ埋まっているか」',
        role: 'トランスフェリン飽和度は、血清鉄÷TIBCで算出されるトランスフェリンの鉄充填率です。鉄の運搬状態を最も直接的に示す指標のひとつで、20%未満では鉄供給不足、45%超ではヘモクロマトーシス（鉄過剰）を疑います。フェリチンと組み合わせることで鉄状態の全体像が見えます。',
        standardRange: '20〜50%',
        optimalRange: '25〜40%',
        highSigns: 'ヘモクロマトーシス・鉄過剰摂取',
        lowSigns: '鉄欠乏性貧血・慢性疾患貧血',
        relatedNutrients: ['iron', 'vitamin-c'],
        relatedGenes: [],
        tips: ['フェリチンと必ずセットで見る', '20%未満は鉄補給を検討', '45%超は鉄の過剰蓄積を疑う'],
    },

    // ===== 血糖・代謝 =====
    {
        slug: 'fasting-glucose',
        name: '空腹時血糖',
        en: 'FASTING GLUCOSE',
        color: '#FBF0CE',
        illustration: '/images/experience_vitality_new.png',
        category: '血糖・代謝',
        tagline: '朝食前の血糖値、エネルギー代謝の出発点',
        role: '空腹時血糖は8時間以上絶食後の血糖値で、インスリン感受性と糖代謝の基本状態を示します。ミトコンドリアにとって血糖の安定は燃料の安定供給に直結します。「正常高値」と呼ばれる95〜100 mg/dLの範囲でも、インスリン抵抗性が進んでいるケースがあるため、インスリン値・HbA1cとセットで評価することが重要です。',
        standardRange: '70〜109 mg/dL',
        optimalRange: '75〜90 mg/dL',
        highSigns: '糖尿病予備群・インスリン抵抗性・睡眠不足・ストレス',
        lowSigns: '過剰なインスリン反応・食事制限のしすぎ',
        relatedNutrients: ['magnesium', 'chromium', 'omega3', 'vitamin-d', 'fiber'],
        relatedGenes: ['comt'],
        tips: ['95以上が続く場合はインスリンも測る', '糖質の質・量と睡眠を見直す', 'マグネシウム・食物繊維は血糖安定に関わる'],
    },
    {
        slug: 'hba1c',
        name: 'HbA1c',
        en: 'HbA1c',
        color: '#FBF0CE',
        illustration: '/images/experience_vitality_new.png',
        category: '血糖・代謝',
        tagline: '過去1〜2ヶ月の「平均血糖」を映す指標',
        role: 'HbA1cは赤血球のヘモグロビンに糖が結合した割合で、過去1〜2ヶ月の平均血糖を反映します。食事前後の変動を受けないため、長期的な血糖管理の指標として最も広く使われます。5.7%以上で糖尿病予備群、6.5%以上で糖尿病と判定されますが、機能医学的には5.3%以下が望ましい最適域とされます。',
        standardRange: '4.3〜5.6%（正常）',
        optimalRange: '4.6〜5.3%',
        highSigns: 'インスリン抵抗性・糖尿病予備群・酸化ストレス増大',
        lowSigns: '（低い場合は概ね良好。貧血では見かけ上低くなることも）',
        relatedNutrients: ['magnesium', 'chromium', 'vitamin-d', 'omega3', 'fiber', 'niacin'],
        relatedGenes: [],
        tips: ['5.7以上は生活改善の強いシグナル', '貧血があると偽低値になる', '3ヶ月ごとに変化をトラッキング'],
    },
    {
        slug: 'fasting-insulin',
        name: '空腹時インスリン',
        en: 'FASTING INSULIN',
        color: '#FBF0CE',
        illustration: '/images/experience_vitality_new.png',
        category: '血糖・代謝',
        tagline: '血糖を下げるホルモンの「下限値」',
        role: '空腹時インスリンは、何も食べていない状態でのインスリン分泌量です。高いほど「同じ血糖を下げるためにより多くのインスリンが必要になっている」インスリン抵抗性を示します。血糖が正常でもインスリンが高い状態が続くと、ミトコンドリア機能低下・肥満・慢性炎症のリスクが上がります。HbA1c・空腹時血糖と組み合わせることで初めて代謝の全体像がわかります。',
        standardRange: '3〜15 μIU/mL',
        optimalRange: '3〜7 μIU/mL',
        highSigns: 'インスリン抵抗性・メタボリックシンドローム・脂肪蓄積',
        lowSigns: '（低値は概ね良好。1型糖尿病等では極低値）',
        relatedNutrients: ['magnesium', 'omega3', 'fiber', 'vitamin-d'],
        relatedGenes: [],
        tips: ['10以上は糖質・睡眠・運動を見直す', 'HOMA-IRで抵抗性を数値化できる', '間欠的断食で改善しやすい'],
    },
    {
        slug: 'homa-ir',
        name: 'HOMA-IR',
        en: 'HOMA-IR',
        color: '#FBF0CE',
        illustration: '/images/experience_vitality_new.png',
        category: '血糖・代謝',
        tagline: 'インスリン抵抗性を数値化する計算指標',
        role: 'HOMA-IRは「空腹時血糖(mg/dL)×空腹時インスリン(μIU/mL)÷405」で算出されるインスリン抵抗性の指標です。1.6以下が理想的、2.5以上でインスリン抵抗性あり、とされます。血糖・HbA1cが正常範囲でも、HOMA-IRが高い「隠れたインスリン抵抗性」は40代のエネルギー低下・脂肪蓄積の主要な原因になります。',
        standardRange: '1.6以下（目安）',
        optimalRange: '1.0以下',
        highSigns: 'インスリン抵抗性・慢性炎症・脂肪肝リスク',
        lowSigns: '（低値は良好）',
        relatedNutrients: ['magnesium', 'omega3', 'fiber', 'vitamin-d', 'niacin'],
        relatedGenes: [],
        tips: ['空腹時血糖×空腹時インスリン÷405で計算', '2.5超は生活習慣の見直しを', '運動・糖質の質・睡眠が鍵'],
    },

    // ===== 脂質 =====
    {
        slug: 'total-cholesterol',
        name: '総コレステロール',
        en: 'TOTAL CHOLESTEROL (TC)',
        color: '#DEEDF7',
        illustration: '/images/for-you-science.png',
        category: '脂質',
        tagline: '細胞膜・ホルモン・胆汁の材料となる脂質の総量',
        role: 'コレステロールは細胞膜・ステロイドホルモン（テストステロン・エストロゲン・コルチゾール）・胆汁酸の材料です。高すぎれば動脈硬化リスクが上がる一方、低すぎても問題があります。総コレステロール単独より、HDL/LDLの内訳と中性脂肪との比率で判断することが重要です。150 mg/dL以下のいわゆる「低コレステロール」も免疫力低下・ホルモン不足の背景になります。',
        standardRange: '130〜219 mg/dL',
        optimalRange: '160〜200 mg/dL',
        highSigns: '動脈硬化リスク・家族性高コレステロール血症',
        lowSigns: 'ホルモン不足・免疫低下・栄養不足',
        relatedNutrients: ['omega3', 'fiber', 'vitamin-d', 'niacin'],
        relatedGenes: ['comt'],
        tips: ['TC単独より内訳(HDL・LDL)で判断', '150以下も問題（低すぎ注意）', '中性脂肪との比率も確認'],
    },
    {
        slug: 'ldl',
        name: 'LDLコレステロール',
        en: 'LDL CHOLESTEROL',
        color: '#DEEDF7',
        illustration: '/images/for-you-science.png',
        category: '脂質',
        tagline: '「悪玉」と呼ばれるが実は組織への配送係',
        role: 'LDLはコレステロールを肝臓から全身の細胞へ運ぶリポタンパクです。「悪玉」と言われますが、酸化されたLDL（酸化LDL）こそが問題で、LDL自体は細胞膜・ホルモン材料の必要な輸送役です。重要なのは「粒子の大きさ」で、小粒子のLDLは酸化されやすく危険。高TG・低HDLの組み合わせで小粒子化が進みやすくなります。',
        standardRange: '60〜139 mg/dL',
        optimalRange: '90〜120 mg/dL（リスク因子なし）',
        highSigns: '動脈硬化リスク（特に酸化LDL・小粒子LDL）',
        lowSigns: '過剰な食事制限・スタチン過剰・ホルモン不足',
        relatedNutrients: ['omega3', 'fiber', 'vitamin-e', 'coq10', 'niacin'],
        relatedGenes: [],
        tips: ['TGが高くHDLが低い時は小粒子LDLを疑う', '酸化ストレスを下げることが大切', 'スタチン使用中はCoQ10に注意'],
    },
    {
        slug: 'hdl',
        name: 'HDLコレステロール',
        en: 'HDL CHOLESTEROL',
        color: '#DEEDF7',
        illustration: '/images/for-you-science.png',
        category: '脂質',
        tagline: '末梢から肝臓へ戻す「回収係」',
        role: 'HDLは末梢組織の余分なコレステロールを肝臓に回収するリポタンパクです。「善玉」と呼ばれ、値が高いほど心血管リスクが下がると長年考えられてきましたが、機能が低下した「機能不全HDL」は高値でもリスクを下げません。HDLを上げる最も効果的な手段は運動・禁煙・オメガ3・アルコール制限です。',
        standardRange: '40 mg/dL以上',
        optimalRange: '男性 55 mg/dL以上、女性 65 mg/dL以上',
        highSigns: '（高値は概ね良好）',
        lowSigns: '心血管リスク増大・インスリン抵抗性・運動不足',
        relatedNutrients: ['omega3', 'niacin', 'coq10'],
        relatedGenes: [],
        tips: ['40未満は強いリスク因子', '有酸素運動が最も有効な上昇手段', 'TG/HDL比（<2が理想）で代謝を評価'],
    },
    {
        slug: 'triglycerides',
        name: '中性脂肪（トリグリセリド）',
        en: 'TRIGLYCERIDES (TG)',
        color: '#DEEDF7',
        illustration: '/images/experience_vitality_new.png',
        category: '脂質',
        tagline: '食事・糖質・アルコールに直撃される脂質',
        role: '中性脂肪は脂肪細胞に蓄えられる脂質で、血液中では食事のエネルギーを運ぶ役割を持ちます。コレステロールよりも食事・生活習慣の影響を受けやすく、糖質（特に果糖）やアルコールを摂りすぎると急上昇します。150 mg/dL以上はインスリン抵抗性・脂肪肝・小粒子LDL増加のサインです。TG/HDL比が代謝の鋭敏な指標になります。',
        standardRange: '30〜149 mg/dL',
        optimalRange: '60〜100 mg/dL',
        highSigns: 'インスリン抵抗性・糖質過剰・アルコール過多・脂肪肝',
        lowSigns: '極低脂肪食・甲状腺機能亢進',
        relatedNutrients: ['omega3', 'fiber', 'niacin'],
        relatedGenes: [],
        tips: ['糖質（特に甘い飲み物・果糖）を減らす', 'TG÷HDLが2以下を目指す', 'オメガ3は中性脂肪を下げる効果あり'],
    },
    {
        slug: 'non-hdl',
        name: 'non-HDLコレステロール',
        en: 'NON-HDL CHOLESTEROL',
        color: '#DEEDF7',
        illustration: '/images/for-you-science.png',
        category: '脂質',
        tagline: 'LDLより広い「動脈硬化を引き起こす脂質」の総量',
        role: 'non-HDLコレステロールは総コレステロールからHDLを引いた値で、LDL・VLDL・IDLなど「動脈に悪影響を与えうる全リポタンパク」の量を反映します。空腹でなくても測れる利点があり、中性脂肪が高い時はLDL単独より正確に心血管リスクを反映することが多いです。LDLが正常でもnon-HDLが高い場合はTG由来のリスクを疑います。',
        standardRange: '90〜169 mg/dL',
        optimalRange: '100〜145 mg/dL',
        highSigns: 'LDL・VLDLの増加・インスリン抵抗性',
        lowSigns: '過度な食事制限',
        relatedNutrients: ['omega3', 'niacin', 'fiber'],
        relatedGenes: [],
        tips: ['空腹でなくても測定できる', 'TGが高い時はLDLよりnon-HDLが重要', 'LDL＋TG由来リスクを合わせて把握'],
    },

    // ===== 肝機能 =====
    {
        slug: 'ast',
        name: 'AST（GOT）',
        en: 'AST / GOT',
        color: '#E4F1E3',
        illustration: '/images/about-illustration.png',
        category: '肝機能',
        tagline: '肝臓・心臓・筋肉の細胞ダメージのサイン',
        role: 'ASTは肝臓・心臓・筋肉に多く含まれる酵素で、細胞が傷つくと血液中に漏れ出します。ASTはALTと異なり筋肉にも多いため、激しい運動後や筋肉疲労でも上昇します。ALTとの比率（AST/ALT比）が重要で、高値では筋肉ダメージ・アルコール性肝炎を疑う場合があります。',
        standardRange: '10〜40 U/L',
        optimalRange: '15〜25 U/L',
        highSigns: '肝炎・アルコール性肝疾患・筋肉ダメージ・心筋梗塞',
        lowSigns: 'ビタミンB6不足（補酵素として必要）',
        relatedNutrients: ['b6', 'magnesium', 'glutathione'],
        relatedGenes: ['gst-gpx'],
        tips: ['ASTとALTを必ずセットで見る', '運動後は一過性に上昇する', 'B6不足でASTが偽低値になることがある'],
    },
    {
        slug: 'alt',
        name: 'ALT（GPT）',
        en: 'ALT / GPT',
        color: '#E4F1E3',
        illustration: '/images/about-illustration.png',
        category: '肝機能',
        tagline: '肝細胞に特化したダメージのより直接的なサイン',
        role: 'ALTは主に肝臓に存在する酵素で、ASTに比べて肝臓ダメージに特異的です。慢性的な上昇は脂肪肝・肝炎・薬剤性肝障害などを示します。PEMTの働きが弱い人や、コリン不足・アルコールが多い環境ではALTが上昇しやすくなります。フルクトース（果糖）の過剰摂取が脂肪肝を経てALT上昇につながるケースも増えています。',
        standardRange: '5〜45 U/L',
        optimalRange: '10〜25 U/L',
        highSigns: '脂肪肝・肝炎・薬剤性肝障害・フルクトース過剰',
        lowSigns: 'ビタミンB6不足',
        relatedNutrients: ['b6', 'choline', 'glutathione', 'omega3'],
        relatedGenes: ['pemt', 'gst-gpx'],
        tips: ['30以上が続く場合は脂肪肝を疑う', '甘い飲み物・アルコールを見直す', 'コリン・B6を確認'],
    },
    {
        slug: 'ggt',
        name: 'γ-GTP',
        en: 'γ-GTP',
        color: '#E4F1E3',
        illustration: '/images/about-illustration.png',
        category: '肝機能',
        tagline: 'アルコールと解毒負荷のバロメーター',
        role: 'γ-GTPはグルタチオンの代謝に関わる酵素で、肝臓・腎臓・膵臓に多く存在します。アルコール摂取・薬剤・肝胆道疾患・酸化ストレスで上昇します。γ-GTPはグルタチオン（GSH）の生成や輸送に関与するため、グルタチオンの消耗が多い状態でも変動します。禁酒後に速やかに下がることが多く、アルコールの影響の確認に使われます。',
        standardRange: '男性 50 U/L以下、女性 30 U/L以下',
        optimalRange: '男性 20 U/L以下、女性 15 U/L以下',
        highSigns: 'アルコール過多・脂肪肝・薬剤性・酸化ストレス',
        lowSigns: '（低値は概ね問題なし）',
        relatedNutrients: ['glutathione', 'nac', 'selenium', 'vitamin-c'],
        relatedGenes: ['gst-gpx'],
        tips: ['禁酒2〜4週間で下がらない場合は肝疾患を疑う', 'グルタチオン系のケアで改善することも', '薬・サプリの影響も確認'],
    },
    {
        slug: 'alp',
        name: 'ALP',
        en: 'ALKALINE PHOSPHATASE (ALP)',
        color: '#E4F1E3',
        illustration: '/images/about-illustration.png',
        category: '肝機能',
        tagline: '骨・肝臓・腸で働く酵素の複合シグナル',
        role: 'ALPは骨・肝臓・腸・胎盤などに存在する酵素で、胆管や骨に問題がある場合に上昇します。特に胆汁うっ滞（胆管の詰まり）で顕著に上昇します。一方、亜鉛不足でALPが低下することが知られており、「低ALP」は亜鉛や栄養不足のサインになります。PEMTの機能が弱い人では、コリン不足による胆汁うっ滞でALPが変動することもあります。',
        standardRange: '38〜113 U/L',
        optimalRange: '50〜90 U/L',
        highSigns: '胆管疾患・骨疾患（骨粗鬆症・ページェット病）・肝炎',
        lowSigns: '亜鉛欠乏・甲状腺機能低下・栄養不足',
        relatedNutrients: ['zinc', 'magnesium', 'vitamin-d'],
        relatedGenes: ['pemt'],
        tips: ['低値は亜鉛不足の可能性', 'γ-GTPと合わせて胆道系を判断', '70以下はミネラル不足を疑う'],
    },
    {
        slug: 'bilirubin',
        name: '総ビリルビン',
        en: 'TOTAL BILIRUBIN',
        color: '#E4F1E3',
        illustration: '/images/about-illustration.png',
        category: '肝機能',
        tagline: '赤血球の分解産物、肝臓の処理能力の指標',
        role: '総ビリルビンは赤血球が分解されてできるヘムの代謝産物で、肝臓で処理されて胆汁として排泄されます。黄疸（皮膚・白目が黄色くなる）はビリルビンが過剰に蓄積した状態です。軽度の高値（0.8〜1.2程度）は体質性（ジルベール症候群）によることも多く、必ずしも問題ではありません。直接・間接ビリルビンの比率で原因が絞れます。',
        standardRange: '0.3〜1.2 mg/dL',
        optimalRange: '0.4〜1.0 mg/dL',
        highSigns: '黄疸・肝炎・胆道閉塞・溶血性貧血',
        lowSigns: '（低値は概ね問題なし）',
        relatedNutrients: ['glutathione', 'b12', 'folate'],
        relatedGenes: [],
        tips: ['1.2以上が続く場合は精査', '間接型高値は溶血・ジルベール症候群を疑う', '直接型高値は胆道系を疑う'],
    },
    {
        slug: 'total-protein',
        name: '総タンパク',
        en: 'TOTAL PROTEIN',
        color: '#E4F1E3',
        illustration: '/images/for-you-wellness.png',
        category: '肝機能',
        tagline: '血液中のタンパク質の総量、栄養状態の大まかな指標',
        role: '総タンパクは血液中に存在するすべてのタンパク質の合計量です。主な成分はアルブミン（約60%）とグロブリンです。低値は栄養不足・肝機能低下・腎臓からの漏出などを示します。高値は慢性炎症・脱水・免疫グロブリンの増加（骨髄腫など）のサインになります。アルブミン単独の方が栄養状態の評価に向いています。',
        standardRange: '6.5〜8.2 g/dL',
        optimalRange: '7.0〜7.8 g/dL',
        highSigns: '脱水・慢性炎症・骨髄腫',
        lowSigns: 'タンパク質不足・肝機能低下・腎臓からの漏出',
        relatedNutrients: ['protein'],
        relatedGenes: [],
        tips: ['アルブミンとセットで評価する', '低い場合はタンパク質の摂取量・消化を確認', '炎症の有無でグロブリン分画が変化'],
    },
    {
        slug: 'albumin',
        name: 'アルブミン',
        en: 'ALBUMIN',
        color: '#E4F1E3',
        illustration: '/images/for-you-wellness.png',
        category: '肝機能',
        tagline: '肝臓が作る主要タンパク、栄養状態の鋭敏な鏡',
        role: 'アルブミンは肝臓で合成される主要なタンパク質で、浸透圧の維持・物質の運搬（薬・脂肪酸・ホルモン）・抗酸化など多くの役割を担います。栄養状態と肝機能の両方を反映する指標で、4.0 g/dL以上が維持されているかどうかが重要な目安です。慢性的な炎症でも低下するため、CRPと合わせた評価が必要です。',
        standardRange: '3.7〜5.5 g/dL',
        optimalRange: '4.3〜5.0 g/dL',
        highSigns: '脱水',
        lowSigns: '栄養不足・肝機能低下・慢性炎症・腎疾患',
        relatedNutrients: ['protein', 'vitamin-c', 'zinc'],
        relatedGenes: [],
        tips: ['4.0以下は早期介入の目安', '慢性炎症があると低くなりやすい', 'タンパク質と炎症の両方を見直す'],
    },

    // ===== 腎機能 =====
    {
        slug: 'creatinine',
        name: 'クレアチニン',
        en: 'CREATININE',
        color: '#DCF1EA',
        illustration: '/images/for-you-science.png',
        category: '腎機能',
        tagline: '筋肉の代謝産物から腎臓のフィルター能力を測る',
        role: 'クレアチニンは筋肉のクレアチンが代謝された産物で、腎臓でフィルタリングされて尿に排泄されます。腎機能が落ちると排泄できず血液中に蓄積します。筋肉量に依存するため、筋肉量の多い人は高め、少ない人（高齢者・女性）は低めに出やすく、eGFRで補正して判断することが重要です。',
        standardRange: '男性 0.65〜1.07 mg/dL、女性 0.46〜0.79 mg/dL',
        optimalRange: '男性 0.7〜1.0 mg/dL、女性 0.5〜0.8 mg/dL',
        highSigns: '腎機能低下・脱水・横紋筋融解症',
        lowSigns: '筋肉量低下（サルコペニア）',
        relatedNutrients: ['protein', 'creatine', 'omega3'],
        relatedGenes: ['nos3'],
        tips: ['eGFRと必ずセットで読む', '低い場合は筋肉量低下の可能性', '水分摂取不足で一過性に上昇'],
    },
    {
        slug: 'egfr',
        name: 'eGFR',
        en: 'eGFR',
        color: '#DCF1EA',
        illustration: '/images/for-you-science.png',
        category: '腎機能',
        tagline: '腎臓の「濾過能力」を年齢・性別で補正した指標',
        role: 'eGFR（推算糸球体濾過量）はクレアチニン値・年齢・性別から腎臓の濾過能力を推定した指標です。60 mL/min/1.73m²未満が3ヶ月以上続くと慢性腎臓病(CKD)と診断されます。eGFRは血圧・血糖・タンパク尿と密接に関連しており、これらの管理がeGFRの低下を防ぎます。',
        standardRange: '60 mL/min/1.73m²以上',
        optimalRange: '90 mL/min/1.73m²以上',
        highSigns: '（高値は概ね良好）',
        lowSigns: '腎機能低下・血圧管理不良・糖尿病性腎症',
        relatedNutrients: ['omega3', 'magnesium', 'vitamin-d'],
        relatedGenes: ['nos3'],
        tips: ['60を下回ったら腎臓専門医へ', '血圧・血糖・タンパク質摂取量の管理が重要', '年1回の確認を'],
    },
    {
        slug: 'bun',
        name: 'BUN（尿素窒素）',
        en: 'BUN',
        color: '#DCF1EA',
        illustration: '/images/for-you-wellness.png',
        category: '腎機能',
        tagline: 'タンパク質の代謝産物から腎機能と水分状態を読む',
        role: 'BUNは体内でアミノ酸が分解されるときにできる尿素の窒素量です。腎臓での排泄が落ちると上昇しますが、タンパク質の摂取量・水分摂取・消化管出血の影響も受けます。クレアチニンとの比率（BUN/Cr比）が10〜20なら腎前性・腎性を鑑別できます。高タンパク食やデハイドレーションでも上昇するため、脱水との区別が重要です。',
        standardRange: '8〜22 mg/dL',
        optimalRange: '10〜18 mg/dL',
        highSigns: '腎機能低下・脱水・高タンパク食・消化管出血',
        lowSigns: 'タンパク質不足・肝機能低下・過水分摂取',
        relatedNutrients: ['protein'],
        relatedGenes: [],
        tips: ['Cr比で脱水vs腎機能低下を区別', '低値はタンパク不足・肝機能低下のサイン', '水分摂取の影響を考慮'],
    },
    {
        slug: 'uric-acid',
        name: '尿酸',
        en: 'URIC ACID',
        color: '#DCF1EA',
        illustration: '/images/for-you-science.png',
        category: '腎機能',
        tagline: 'プリン体の最終代謝産物、痛風と炎症の指標',
        role: '尿酸はDNA・RNAのプリン塩基が分解されてできる最終産物で、腎臓から排泄されます。高値が続くと関節に結晶が蓄積して痛風を起こします。また高尿酸血症はインスリン抵抗性・心血管リスク・腎機能低下とも関連します。意外に見落とされがちなのは果糖（フルクトース）が尿酸を急上昇させる点です。',
        standardRange: '男性 3.0〜7.0 mg/dL、女性 2.0〜6.0 mg/dL',
        optimalRange: '男性 4.0〜6.0 mg/dL、女性 3.0〜5.0 mg/dL',
        highSigns: '痛風・腎結石・インスリン抵抗性・心血管リスク',
        lowSigns: '抗酸化能の低下（尿酸は弱い抗酸化物質でもある）',
        relatedNutrients: ['vitamin-c', 'fiber'],
        relatedGenes: [],
        tips: ['甘い飲み物（果糖）を減らす', '水分を十分に摂る', '6.0以下を維持できると良い'],
    },

    // ===== 甲状腺 =====
    {
        slug: 'tsh',
        name: 'TSH（甲状腺刺激ホルモン）',
        en: 'TSH',
        color: '#FAF3D6',
        illustration: '/images/experience_vitality_new.png',
        category: '甲状腺',
        tagline: '甲状腺の活動を指示する「司令ホルモン」',
        role: 'TSHは脳下垂体から分泌され、甲状腺に「ホルモンを作れ」と指示するホルモンです。甲状腺機能低下症では甲状腺が反応しないためTSHが高くなり、機能亢進症では過剰分泌を抑えるためTSHが低くなります。機能医学的には、一般基準値（0.5〜4.0）内でも1.0〜2.0の範囲が最適とされます。',
        standardRange: '0.5〜4.0 mIU/L',
        optimalRange: '1.0〜2.0 mIU/L',
        highSigns: '甲状腺機能低下（疲労・冷え・体重増加・気分の落ち込み）',
        lowSigns: '甲状腺機能亢進（動悸・体重減少・不眠・手の震え）',
        relatedNutrients: ['selenium', 'zinc', 'vitamin-d', 'iron'],
        relatedGenes: [],
        tips: ['2.5以上は機能低下傾向を疑う', 'FT3・FT4と合わせて総合判断', 'セレン・亜鉛・鉄が甲状腺機能を支える'],
    },
    {
        slug: 'ft3',
        name: 'FT3（遊離トリヨードサイロニン）',
        en: 'FREE T3 (FT3)',
        color: '#FAF3D6',
        illustration: '/images/experience_vitality_new.png',
        category: '甲状腺',
        tagline: '細胞で実際に働く「活性型甲状腺ホルモン」',
        role: 'FT3は体内で最もパワフルに代謝・体温・エネルギー産生を駆動する活性型甲状腺ホルモンです。T4（FT4）がセレン依存性の酵素で変換されて作られます。TSHやFT4が正常でもFT3が低いケースが見落とされやすく、疲労・冷え・体重管理の難しさとして現れます。セレン不足・炎症・低糖質過度な食事でT4→T3の変換が落ちることがあります。',
        standardRange: '2.3〜4.0 pg/mL',
        optimalRange: '3.0〜4.0 pg/mL',
        highSigns: '甲状腺機能亢進・T3中毒症',
        lowSigns: '疲労・冷え・代謝低下（T4→T3変換不全含む）',
        relatedNutrients: ['selenium', 'zinc', 'iron', 'vitamin-d'],
        relatedGenes: [],
        tips: ['FT3が低くTSH正常でも機能低下症状が出る', 'セレンがT4→T3変換に必要', '極端な低糖質で変換が落ちることがある'],
    },
    {
        slug: 'ft4',
        name: 'FT4（遊離サイロキシン）',
        en: 'FREE T4 (FT4)',
        color: '#FAF3D6',
        illustration: '/images/experience_vitality_new.png',
        category: '甲状腺',
        tagline: '甲状腺が作る「前駆型」ホルモン',
        role: 'FT4は甲状腺が主に分泌するホルモンで、末梢の組織でセレン依存性の脱ヨード酵素によってFT3に変換されて初めて活性化します。TSHが高くFT4が低い場合は明確な甲状腺機能低下、TSHが正常でもFT4が低い場合は視床下部・下垂体の問題を疑います。FT4単独ではなくTSH・FT3・抗体（TPO抗体等）と合わせた評価が重要です。',
        standardRange: '0.9〜1.7 ng/dL',
        optimalRange: '1.1〜1.6 ng/dL',
        highSigns: '甲状腺機能亢進・過剰補充',
        lowSigns: '甲状腺機能低下・栄養不足',
        relatedNutrients: ['selenium', 'zinc', 'iron', 'iodine'],
        relatedGenes: [],
        tips: ['TSH↑・FT4↓で明確な機能低下', 'TPO抗体も一緒に測ると橋本病の有無がわかる', 'FT3変換のためにセレンを確認'],
    },

    // ===== 炎症・メチレーション =====
    {
        slug: 'hscrp',
        name: '高感度CRP',
        en: 'HIGH-SENSITIVITY CRP (hs-CRP)',
        color: '#FCE8D9',
        illustration: '/images/for-you-science.png',
        category: '炎症・メチレーション',
        tagline: '慢性炎症の「温度計」',
        role: '高感度CRP（hs-CRP）は炎症反応で肝臓が産生するタンパク質で、通常の検査より微量の炎症も捉えられます。心血管疾患・認知症・がん・代謝疾患のリスク指標として重視されています。1 mg/L以下が低リスク、3 mg/L以上が高リスクの目安です。慢性炎症はミトコンドリアの機能を直接低下させるため、エネルギー低下の背景を探る上で重要な指標です。',
        standardRange: '0.1〜3.0 mg/L（慣用基準）',
        optimalRange: '0.5 mg/L以下',
        highSigns: '慢性炎症・感染症・肥満・インスリン抵抗性・歯周病',
        lowSigns: '（低値は良好）',
        relatedNutrients: ['omega3', 'vitamin-d', 'magnesium', 'glutathione', 'vitamin-c'],
        relatedGenes: ['comt'],
        tips: ['1以下を目指す', '食事・睡眠・運動・口腔ケアが直接影響する', 'フェリチンと合わせて炎症を多角的に見る'],
    },
    {
        slug: 'homocysteine',
        name: 'ホモシステイン',
        en: 'HOMOCYSTEINE',
        color: '#FCE8D9',
        illustration: '/images/for-you-science.png',
        category: '炎症・メチレーション',
        tagline: 'メチレーション機能の直接的なアウトカム',
        role: 'ホモシステインはアミノ酸メチオニンの代謝中間産物で、MTHFRを中心とするメチレーション回路で処理されます。高値は動脈硬化・認知症・うつ・骨粗鬆症リスクの増大と強く関連します。葉酸・B12・B6が不足するとホモシステインが蓄積するため、これらの栄養状態の「総合アウトカム」として使えます。MTHFRの働きが弱い人は高くなりやすい代表的な指標です。',
        standardRange: '4〜15 μmol/L',
        optimalRange: '4〜8 μmol/L',
        highSigns: '動脈硬化・認知症リスク・うつ・葉酸/B12/B6不足',
        lowSigns: '（低値は良好）',
        relatedNutrients: ['folate', 'b12', 'b6', 'nac', 'magnesium'],
        relatedGenes: ['mthfr', 'comt'],
        tips: ['10以上は葉酸・B12・B6を補充', 'MTHFRが気になる人は定期的に測定', '心血管リスクの「隠れた指標」として重要'],
    },
    {
        slug: 'fibrinogen',
        name: 'フィブリノーゲン',
        en: 'FIBRINOGEN',
        color: '#FCE8D9',
        illustration: '/images/for-you-science.png',
        category: '炎症・メチレーション',
        tagline: '血液を固める材料であり、炎症マーカーでもある',
        role: 'フィブリノーゲンは血液凝固に必要なタンパク質で、傷口で血栓を作る際に使われます。同時に急性相タンパクとして炎症時に肝臓で産生量が増えます。高値は慢性炎症・血栓リスク・心血管疾患と関連します。喫煙・肥満・代謝症候群で上昇しやすく、hs-CRPと並ぶ慢性炎症の指標として評価されます。',
        standardRange: '150〜350 mg/dL',
        optimalRange: '180〜280 mg/dL',
        highSigns: '慢性炎症・血栓リスク・喫煙・代謝症候群',
        lowSigns: '肝機能低下・血液凝固異常',
        relatedNutrients: ['omega3', 'vitamin-e', 'vitamin-c'],
        relatedGenes: ['nos3'],
        tips: ['hs-CRPと合わせて慢性炎症を評価', '喫煙・肥満が最大の上昇要因', 'オメガ3が血液サラサラ効果で間接的に影響'],
    },

    // ===== ビタミン =====
    {
        slug: 'vitamin-d-serum',
        name: 'ビタミンD（25-OH-D）',
        en: '25-HYDROXYVITAMIN D',
        color: '#EAE4F2',
        illustration: '/images/experience_vitality_new.png',
        category: 'ビタミン',
        tagline: 'ビタミンDの体内貯蔵量を示す主要指標',
        role: '25-ヒドロキシビタミンD（25-OH-D）は血液中で最も豊富に存在するビタミンD代謝産物で、体内のビタミンD貯蔵量を最もよく反映します。骨代謝・免疫調整・筋力・気分・炎症調節に関わる受容体は全身の細胞に存在します。一般基準の「20 ng/mL以上」より、機能医学的には「40〜60 ng/mL」が最適域とされます。',
        standardRange: '20 ng/mL以上（一般基準）',
        optimalRange: '40〜60 ng/mL',
        highSigns: '過剰補充（毒性：高カルシウム血症）',
        lowSigns: '免疫低下・筋力低下・気分の落ち込み・骨密度低下',
        relatedNutrients: ['vitamin-d', 'magnesium', 'vitamin-k2'],
        relatedGenes: [],
        tips: ['30以下は補充を検討', 'K2・マグネシウムと組み合わせる', '3〜4ヶ月ごとに確認するのが目安'],
    },
    {
        slug: 'vitamin-b12-serum',
        name: 'ビタミンB12（血清）',
        en: 'SERUM VITAMIN B12',
        color: '#EAE4F2',
        illustration: '/images/for-you-science.png',
        category: 'ビタミン',
        tagline: '神経とメチレーションを守るビタミンの「残量」',
        role: '血清ビタミンB12は体内のB12貯蔵量の目安を示しますが、測定値が正常範囲でも機能的に不足している「機能的B12欠乏」が存在します。より鋭敏な指標はメチルマロン酸（MMA）やホモシステインの上昇です。菜食主義者・高齢者・胃薬長期服用者は特にリスクが高く、神経症状（しびれ・物忘れ）として現れる前に確認が必要です。',
        standardRange: '200〜950 pg/mL',
        optimalRange: '500〜900 pg/mL',
        highSigns: '（高値は概ね問題なし。肝疾患・一部の血液疾患で高値）',
        lowSigns: '大球性貧血・末梢神経障害・認知機能低下',
        relatedNutrients: ['b12', 'folate'],
        relatedGenes: ['mthfr', 'pemt'],
        tips: ['400以下は機能的不足の可能性', 'ホモシステイン・MMAと合わせて評価', '菜食・胃薬服用中は積極的に確認'],
    },
    {
        slug: 'folate-serum',
        name: '葉酸（血清）',
        en: 'SERUM FOLATE',
        color: '#EAE4F2',
        illustration: '/images/for-you-science.png',
        category: 'ビタミン',
        tagline: 'メチレーション回路の燃料レベルを確認する',
        role: '血清葉酸はDNA合成・修復とメチレーション回路に必要な葉酸の循環レベルを示します。赤血球葉酸は長期的な葉酸状態をより正確に反映しますが、血清値も重要な指標です。MTHFRの活性が低い人は葉酸を活性型に変換しにくいため、血清値が正常でも機能的に不足していることがあります。ホモシステイン値との組み合わせで機能状態を推測できます。',
        standardRange: '3.0〜20.0 ng/mL',
        optimalRange: '6.0〜16.0 ng/mL',
        highSigns: '（高値は概ね問題なし）',
        lowSigns: '大球性貧血・神経管欠損リスク・ホモシステイン上昇',
        relatedNutrients: ['folate', 'b12', 'b6'],
        relatedGenes: ['mthfr'],
        tips: ['ホモシステインと合わせて機能を評価', 'MTHFRが気になる人は活性型(5-MTHF)で補う', 'B12とセットで確認する'],
    },

    // ===== ミネラル =====
    {
        slug: 'zinc-serum',
        name: '亜鉛（血清）',
        en: 'SERUM ZINC',
        color: '#DCF1EA',
        illustration: '/images/for-you-wellness.png',
        category: 'ミネラル',
        tagline: '免疫・ホルモン・酵素の要、血中亜鉛レベル',
        role: '血清亜鉛は体内亜鉛状態の目安ですが、亜鉛の多くは細胞内に存在するため、血清値が正常でも細胞レベルでは不足していることがあります。慢性的な炎症・ストレス・下痢・過剰な汗で低下しやすく、味覚・嗅覚の低下・皮膚荒れ・免疫低下・テストステロン低下として現れます。ALPが低値の時も亜鉛不足を疑う手がかりになります。',
        standardRange: '80〜130 μg/dL',
        optimalRange: '90〜120 μg/dL',
        highSigns: '過剰摂取（銅欠乏・免疫抑制）',
        lowSigns: '免疫低下・味覚異常・肌荒れ・テストステロン低下',
        relatedNutrients: ['zinc', 'copper', 'protein'],
        relatedGenes: ['dao', 'gst-gpx'],
        tips: ['ALPが低い時は亜鉛不足を疑う', '過剰摂取で銅が枯渇する', '動物性食品が最も吸収しやすい'],
    },
    {
        slug: 'rbc-magnesium',
        name: 'マグネシウム（赤血球内）',
        en: 'RBC MAGNESIUM',
        color: '#DCF1EA',
        illustration: '/images/for-you-wellness.png',
        category: 'ミネラル',
        tagline: '血清より正確、細胞内マグネシウムの実態',
        role: '体内マグネシウムの99%は細胞内にあり、血清マグネシウムは全体の1%以下。そのため血清値が正常でも細胞内では不足していることがあります。赤血球内マグネシウムは細胞内の状態をより正確に反映する、より有用な指標です。300種以上の酵素反応の補因子として、エネルギー産生・神経機能・筋肉弛緩・血糖調節に関わります。',
        standardRange: '4.2〜6.8 mg/dL（赤血球内）',
        optimalRange: '5.5〜6.5 mg/dL',
        highSigns: '腎機能低下・過剰補充',
        lowSigns: 'エネルギー低下・筋けいれん・不眠・イライラ',
        relatedNutrients: ['magnesium', 'vitamin-d'],
        relatedGenes: ['comt', 'maoa', 'nos3'],
        tips: ['血清値より赤血球内が正確', '血清値が正常でも症状がある時に測る', 'グリシン酸・クエン酸型が吸収良好'],
    },
    {
        slug: 'serum-copper',
        name: '銅（血清）',
        en: 'SERUM COPPER',
        color: '#DCF1EA',
        illustration: '/images/for-you-science.png',
        category: 'ミネラル',
        tagline: '抗酸化・鉄代謝・神経を支える微量ミネラルの残量',
        role: '血清銅は体内の銅状態を示す指標です。銅は抗酸化酵素SODの必須成分、鉄の利用を助けるセルロプラスミンの材料、ミトコンドリア電子伝達系の酵素成分として重要です。亜鉛サプリの長期摂取は銅と拮抗して銅を枯渇させることがあります。一方、過剰な銅は酸化ストレスを増大させるため、過不足両方の管理が必要です。',
        standardRange: '70〜140 μg/dL',
        optimalRange: '80〜120 μg/dL',
        highSigns: '炎症・ウィルソン病・エストロゲン優位',
        lowSigns: '亜鉛過剰・貧血(鉄抵抗性)・骨の弱り',
        relatedNutrients: ['copper', 'zinc', 'glutathione'],
        relatedGenes: ['dao', 'gst-gpx'],
        tips: ['亜鉛サプリ長期使用中は銅も確認', '亜鉛:銅の理想比は約8:1', 'セルロプラスミンと合わせると精度が上がる'],
    },

    // ===== ホルモン =====
    {
        slug: 'total-testosterone',
        name: 'テストステロン（総）',
        en: 'TOTAL TESTOSTERONE',
        color: '#FCE3D4',
        illustration: '/images/for-you-business.png',
        category: 'ホルモン',
        tagline: '筋肉・エネルギー・性欲・気分を支える主要ホルモン',
        role: 'テストステロンは男女ともに筋肉の維持・骨密度・エネルギー・性欲・気分・認知機能に関わる重要なホルモンです。加齢とともに低下しますが、40代以降でも生活習慣（睡眠・運動・栄養・ストレス管理）によって維持できます。COMTの働きが遅い人はエストロゲンとの代謝バランスに影響が出ることがあります。総値と遊離値を合わせて評価します。',
        standardRange: '男性 250〜1000 ng/dL、女性 15〜70 ng/dL',
        optimalRange: '男性 500〜900 ng/dL、女性 20〜50 ng/dL',
        highSigns: '多嚢胞性卵巣症候群（女性）・外因性補充過剰',
        lowSigns: '疲労・筋力低下・性欲低下・気分の落ち込み・骨密度低下',
        relatedNutrients: ['zinc', 'vitamin-d', 'magnesium', 'protein'],
        relatedGenes: ['comt'],
        tips: ['SHBG（性ホルモン結合グロブリン）も合わせて確認', '睡眠7〜9時間が産生に最も影響', '遊離テストステロンも同時に測る'],
    },
    {
        slug: 'free-testosterone',
        name: '遊離テストステロン',
        en: 'FREE TESTOSTERONE',
        color: '#FCE3D4',
        illustration: '/images/for-you-business.png',
        category: 'ホルモン',
        tagline: '実際に細胞で使えるテストステロンの「有効分」',
        role: 'テストステロンの大部分はSHBGやアルブミンと結合しており、実際に細胞で使えるのは「遊離型（約2〜3%）」だけです。総テストステロンが正常でもSHBGが高いと遊離型が少なく、症状が出ることがあります。加齢・インスリン抵抗性・肥満でSHBGのバランスが変化するため、遊離テストステロンの確認が機能評価に欠かせません。',
        standardRange: '男性 8.5〜21.5 pg/mL、女性 0.4〜3.7 pg/mL（測定法により異なる）',
        optimalRange: '男性 13〜20 pg/mL、女性 1.0〜3.0 pg/mL',
        highSigns: '過剰補充',
        lowSigns: 'SHBG高値・加齢・疲労・活力低下',
        relatedNutrients: ['zinc', 'vitamin-d', 'magnesium'],
        relatedGenes: ['comt'],
        tips: ['SHBGも同時に測定する', '総テストステロンと遊離型の乖離に注目', 'インスリン抵抗性の改善でSHBGが変化する'],
    },
    {
        slug: 'dhea-s',
        name: 'DHEA-S',
        en: 'DHEA-SULFATE',
        color: '#FCE3D4',
        illustration: '/images/for-you-business.png',
        category: 'ホルモン',
        tagline: '副腎が作るホルモン、エネルギーと活力の土台',
        role: 'DHEA-S（硫酸デヒドロエピアンドロステロン）は副腎皮質から分泌されるステロイドホルモンで、テストステロンやエストロゲンの前駆物質です。20代にピークを迎え、40代以降は急速に低下します。慢性ストレスでコルチゾール産生が優先されると、DHEAが相対的に低下（「プレグネノロンスチール」）します。低DHEA-Sは疲労感・免疫力低下・気分の落ち込みとつながります。',
        standardRange: '男性 80〜560 μg/dL、女性 35〜430 μg/dL（年齢により異なる）',
        optimalRange: '40代男性 200〜350 μg/dL、40代女性 100〜250 μg/dL',
        highSigns: '副腎過活動・PCOS',
        lowSigns: '慢性ストレス・副腎疲労・加齢・活力低下',
        relatedNutrients: ['vitamin-d', 'magnesium', 'zinc'],
        relatedGenes: ['comt'],
        tips: ['コルチゾールとの比率が重要', 'DHEA/コルチゾール比でストレス負荷を評価', 'ストレス管理が最も有効な介入'],
    },
    {
        slug: 'cortisol',
        name: 'コルチゾール',
        en: 'CORTISOL',
        color: '#FCE3D4',
        illustration: '/images/for-you-business.png',
        category: 'ホルモン',
        tagline: 'ストレスに応じて血糖を上げる「緊急対応ホルモン」',
        role: 'コルチゾールは副腎皮質から分泌されるストレスホルモンで、血糖の上昇・炎症の抑制・免疫の調整に関わります。朝に高く夜に低いという日内リズムを持ちます。慢性的なストレスで常時高値になると、筋肉分解・インスリン抵抗性・免疫抑制・睡眠障害・腹部脂肪の蓄積につながります。COMTの働きが遅い人はカテコールアミン処理に影響し、コルチゾール反応が強くなることがあります。',
        standardRange: '朝: 6〜23 μg/dL（測定タイミングで大きく変化）',
        optimalRange: '朝: 12〜20 μg/dL',
        highSigns: '慢性ストレス・クッシング症候群・不眠・腹部肥満',
        lowSigns: '副腎疲労・アジソン病・慢性疲労',
        relatedNutrients: ['vitamin-c', 'magnesium', 'b5'],
        relatedGenes: ['comt', 'maoa'],
        tips: ['必ず朝（起床後30〜60分）に測定', 'DHEA-Sとの比率も評価する', 'ストレス管理・睡眠が最優先'],
    },
    {
        slug: 'estradiol',
        name: 'エストラジオール（E2）',
        en: 'ESTRADIOL (E2)',
        color: '#FCE3D4',
        illustration: '/images/for-you-wellness.png',
        category: 'ホルモン',
        tagline: '最も強力なエストロゲン、骨・血管・脳を守る',
        role: 'エストラジオール(E2)は最も生物活性の強い女性ホルモンで、女性では卵巣・男性では脂肪組織でも産生されます。骨密度の維持・血管の保護・認知機能・気分・性欲・膣粘膜の健康に関わります。COMTの働きが遅い人ではエストラジオールの分解が滞り、エストロゲン優位の症状（PMS・むくみ・体重増加）が強まることがあります。更年期前後は変動が大きく、LH・FSHと合わせた評価が必要です。',
        standardRange: '女性（卵胞期）: 20〜170 pg/mL（生理周期で変動）、男性: 10〜40 pg/mL',
        optimalRange: '女性（卵胞期）: 40〜100 pg/mL、男性: 15〜30 pg/mL',
        highSigns: 'エストロゲン優位・PMS・乳腺過敏・体重増加（特に腰周り）',
        lowSigns: '更年期症状・骨密度低下・潮紅・気分の落ち込み',
        relatedNutrients: ['magnesium', 'folate', 'b12'],
        relatedGenes: ['comt', 'pemt'],
        tips: ['LH・FSH・プロゲステロンとセットで評価', 'COMTが遅い人はエストロゲン優位になりやすい', 'アブラナ科野菜（DIM）でエストロゲン代謝を助ける'],
    },
    {
        slug: 'igf1',
        name: 'IGF-1',
        en: 'INSULIN-LIKE GROWTH FACTOR-1',
        color: '#FCE3D4',
        illustration: '/images/for-you-business.png',
        category: 'ホルモン',
        tagline: '成長ホルモンの作用を仲介する「若さの代理指標」',
        role: 'IGF-1（インスリン様成長因子-1）は成長ホルモン(GH)の刺激で肝臓が産生するペプチドホルモンです。筋肉・骨の成長・修復、脂肪の分解、細胞の修復・再生を促進します。加齢とともに低下し、40代以降では筋肉量の維持や回復力に影響します。過剰は腫瘍リスク増大につながる一方、低すぎると筋力低下・代謝低下・回復の遅れを招きます。',
        standardRange: '成人: 70〜250 ng/mL（年齢によって変化）',
        optimalRange: '40代: 130〜220 ng/mL',
        highSigns: '先端巨大症・成長ホルモン過剰・腫瘍リスク',
        lowSigns: '筋肉量低下・回復力低下・GH分泌不全',
        relatedNutrients: ['protein', 'zinc', 'vitamin-d'],
        relatedGenes: [],
        tips: ['タンパク質の充足とスリープがIGF-1産生を支える', 'HIITや筋トレで成長ホルモン分泌を促す', '高すぎても問題なのでバランスを'],
    },
];

export function getBiomarkerBySlug(slug: string): Biomarker | undefined {
    return biomarkers.find((b) => b.slug === slug);
}

// カテゴリ別にグループ化
export function getBiomarkersByCategory(): Record<string, Biomarker[]> {
    return biomarkers.reduce((acc, b) => {
        if (!acc[b.category]) acc[b.category] = [];
        acc[b.category].push(b);
        return acc;
    }, {} as Record<string, Biomarker[]>);
}
