// ライブラリ全体の「静的ページ」単一レジストリ。
// sitemap.ts と searchIndex.ts の両方がこの1ファイルを参照する。
// ページを追加したら、ここに1行足すだけで sitemap と横断検索の双方に反映される。
// （遺伝子・栄養素・食べ物などのデータ駆動コレクションは各 lib/*.ts が別途供給）

export interface StaticPage {
    path: string;
    priority: number;
    changeFrequency: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
    // search を持つページだけが横断検索に載る（コンセプト・しくみ解説など）
    search?: { title: string; sub?: string; group: string };
}

export const staticPages: StaticPage[] = [
    { path: '/', priority: 1, changeFrequency: 'daily' },
    { path: "/acid-alkaline", priority: 0.6, changeFrequency: 'monthly', search: { title: "酸性・アルカリ性（pH）", sub: "血液pHの調節・アルカリ性食品の誤解", group: "しくみ" } },
    { path: "/anxiety", priority: 0.6, changeFrequency: 'monthly', search: { title: "不安と体", sub: "Anxiety", group: "心とからだ" } },
    { path: "/atp", priority: 0.6, changeFrequency: 'monthly', search: { title: "ATP", sub: "エネルギー通貨", group: "しくみ" } },
    { path: "/author", priority: 0.5, changeFrequency: 'yearly' },
    { path: "/autonomic-nervous-system", priority: 0.6, changeFrequency: 'monthly', search: { title: "自律神経", sub: "Autonomic Nervous System", group: "しくみ" } },
    { path: "/autophagy", priority: 0.6, changeFrequency: 'monthly', search: { title: "オートファジー", sub: "Autophagy", group: "しくみ" } },
    { path: "/balance", priority: 0.6, changeFrequency: 'monthly', search: { title: "バランス（中庸）", sub: "体は「ちょうどよさ」でできている", group: "考え方" } },
    { path: "/biomarkers", priority: 0.7, changeFrequency: 'monthly' },
    { path: "/biomarkers/reader", priority: 0.8, changeFrequency: 'monthly', search: { title: "検査値リーダー", sub: "血液検査の数値を入れて、基準値・理想値との位置を確かめる", group: "身体の地図" } },
    { path: "/black-jack", priority: 0.6, changeFrequency: 'monthly', search: { title: "ブラック・ジャックを読む", sub: "無免許医という問い／免許・医療の値段・治せなさ", group: "考え方" } },
    { path: "/blood-sugar", priority: 0.6, changeFrequency: 'monthly', search: { title: "血糖コントロール", sub: "Blood Sugar", group: "しくみ" } },
    { path: "/books", priority: 0.6, changeFrequency: 'monthly', search: { title: "おすすめ書籍", sub: "Recommended Books / もっと深く知るための本", group: "考え方" } },
    { path: "/caffeine", priority: 0.6, changeFrequency: 'monthly', search: { title: "カフェインとの付き合い方", sub: "量・タイミング・代謝の個人差", group: "生活習慣" } },
    { path: "/calories", priority: 0.6, changeFrequency: 'monthly', search: { title: "カロリーの誤解", sub: "「1kcalは1kcal」は本当？", group: "食べ物" } },
    { path: "/cannabis", priority: 0.4, changeFrequency: 'monthly', search: { title: "大麻をめぐる歴史と世界の動き", sub: "歴史・法政策（中立解説・日本では違法）", group: "考え方" } },
    { path: "/caution-foods", priority: 0.7, changeFrequency: 'monthly', search: { title: "気をつけたい食品", sub: "Caution Foods", group: "食べ物" } },
    { path: "/cgm", priority: 0.6, changeFrequency: 'monthly', search: { title: "血糖モニタリング（CGM）", sub: "フリースタイルリブレで血糖を可視化する", group: "生活習慣" } },
    { path: "/check", priority: 0.9, changeFrequency: 'monthly' },
    { path: "/chrono-nutrition", priority: 0.6, changeFrequency: 'monthly', search: { title: "時間栄養学（クロノニュートリション）", sub: "いつ食べるかで変わる体", group: "しくみ" } },
    { path: "/chronic-kidney-disease", priority: 0.7, changeFrequency: 'monthly', search: { title: "慢性腎臓病（CKD）", sub: "eGFR・クレアチニン・尿たんぱくの見方", group: "しくみ" } },
    { path: "/circadian-rhythm", priority: 0.6, changeFrequency: 'monthly', search: { title: "概日リズム（体内時計）", sub: "Circadian Rhythm", group: "しくみ" } },
    { path: "/conditions", priority: 0.8, changeFrequency: 'weekly', search: { title: "不調・現代病を読み解く", sub: "鉄欠乏・インスリン抵抗性・脂肪肝・更年期…病態の索引", group: "身体の地図" } },
    { path: "/counterculture", priority: 0.4, changeFrequency: 'monthly', search: { title: "対抗文化が生んだもの", sub: "フラワームーブメントからパソコンまで", group: "考え方" } },
    { path: "/detox", priority: 0.6, changeFrequency: 'monthly', search: { title: "デトックス（解毒）", sub: "Detox", group: "しくみ" } },
    { path: "/diabetes", priority: 0.6, changeFrequency: 'monthly', search: { title: "糖尿病とは", sub: "種類・サイン・予防と、境界型のうちにできること", group: "しくみ" } },
    { path: "/digestion", priority: 0.6, changeFrequency: 'monthly', search: { title: "消化・吸収", sub: "Digestion & Absorption", group: "しくみ" } },
    { path: "/dyslipidemia", priority: 0.7, changeFrequency: 'monthly', search: { title: "脂質異常症とは", sub: "LDL・HDL・中性脂肪をまとめて読む", group: "しくみ" } },
    { path: "/electron-transport-chain", priority: 0.6, changeFrequency: 'monthly', search: { title: "電子伝達系", sub: "Electron Transport Chain", group: "しくみ" } },
    { path: "/electrotherapy", priority: 0.6, changeFrequency: 'monthly', search: { title: "電気療法とミトコンドリア", sub: "整体・接骨院の「電気」を事実ベースで／低周波・EMS・微弱電流", group: "考え方" } },
    { path: "/energy", priority: 0.7, changeFrequency: 'monthly', search: { title: "エネルギーとは", sub: "Energy / 疲れにくさの正体", group: "しくみ" } },
    { path: "/enzymes", priority: 0.6, changeFrequency: 'monthly', search: { title: "酵素", sub: "触媒・消化酵素・代謝酵素・補酵素／酵素ドリンクの誤解", group: "しくみ" } },
    { path: "/exercise", priority: 0.6, changeFrequency: 'monthly', search: { title: "運動", sub: "Exercise", group: "生活習慣" } },
    { path: "/fasting", priority: 0.6, changeFrequency: 'monthly', search: { title: "食べない時間の力", sub: "断食・空腹がもたらすもの、向く人・向かない人", group: "生活習慣" } },
    { path: "/fatty-liver", priority: 0.6, changeFrequency: 'monthly', search: { title: "脂肪肝（MASLD）", sub: "沈黙の現代病・お酒を飲まなくてもなる脂肪肝", group: "しくみ" } },
    { path: "/food-journey", priority: 0.7, changeFrequency: 'monthly', search: { title: "食べてから、動くまで", sub: "消化・吸収・代謝・排出の全体像（インフォグラフィック）", group: "しくみ" } },
    { path: "/foods", priority: 0.7, changeFrequency: 'monthly' },
    { path: "/genes", priority: 0.7, changeFrequency: 'monthly' },
    { path: "/glycation", priority: 0.6, changeFrequency: 'monthly', search: { title: "糖化（こげる）", sub: "Glycation", group: "しくみ" } },
    { path: "/glycolysis", priority: 0.6, changeFrequency: 'monthly', search: { title: "解糖系", sub: "Glycolysis", group: "しくみ" } },
    { path: "/gut-brain", priority: 0.6, changeFrequency: 'monthly', search: { title: "腸脳相関", sub: "Gut-Brain Axis", group: "しくみ" } },
    { path: "/gut-health", priority: 0.7, changeFrequency: 'monthly', search: { title: "腸内環境（腸活）", sub: "Gut Health / 腸内細菌・マイクロバイオーム", group: "しくみ" } },
    { path: "/gut-troubles", priority: 0.6, changeFrequency: 'monthly', search: { title: "気になる腸のキーワード", sub: "グルテン・カゼイン・リーキーガット・SIBO", group: "しくみ" } },
    { path: "/gym-boom", priority: 0.6, changeFrequency: 'monthly', search: { title: "ジムの乱立を読む", sub: "なぜ増える？運動を「買う」時代を中立に", group: "考え方" } },
    { path: "/harmony", priority: 0.6, changeFrequency: 'monthly', search: { title: "健康と和", sub: "「和」という言葉から健康を読み解く", group: "考え方" } },
    { path: "/health-counterculture", priority: 0.6, changeFrequency: 'monthly', search: { title: "健康とは、カウンターカルチャーである", sub: "身体から始める静かな反抗", group: "考え方" } },
    { path: "/health-philosophy", priority: 0.8, changeFrequency: 'monthly', search: { title: "健康とは", sub: "Mitoflow40の健康哲学", group: "考え方" } },
    { path: "/health-check-guide", priority: 0.8, changeFrequency: 'monthly', search: { title: "40代の健康診断の読み方", sub: "結果票を次の行動につなげる", group: "身体の地図" } },
    { path: "/histamine", priority: 0.6, changeFrequency: 'monthly', search: { title: "ヒスタミンとは", sub: "アレルギー・胃酸・脳・分解酵素（DAO/HNMT）", group: "しくみ" } },
    { path: "/hormones", priority: 0.7, changeFrequency: 'monthly' },
    { path: "/hsp", priority: 0.6, changeFrequency: 'monthly', search: { title: "HSP（繊細さん）と体・遺伝子", sub: "感受性の強さを、体と遺伝子から読む", group: "心とからだ" } },
    { path: "/hypertension", priority: 0.7, changeFrequency: 'monthly', search: { title: "高血圧とは", sub: "家庭血圧・原因・血管への影響と生活の整え方", group: "しくみ" } },
    { path: "/inflammation", priority: 0.6, changeFrequency: 'monthly', search: { title: "炎症", sub: "Inflammation", group: "しくみ" } },
    { path: "/integrative-medicine", priority: 0.6, changeFrequency: 'monthly', search: { title: "統合医療とは", sub: "西洋医学と補完療法を中立に", group: "考え方" } },
    { path: "/insulin-resistance", priority: 0.7, changeFrequency: 'monthly', search: { title: "インスリン抵抗性とは", sub: "血糖が上がる前に起きていること", group: "しくみ" } },
    { path: "/jogging", priority: 0.6, changeFrequency: 'monthly', search: { title: "ジョギングと体", sub: "効果・「膝に悪い」の真偽・走る量", group: "生活習慣" } },
    { path: "/journal", priority: 0.9, changeFrequency: 'daily' },
    { path: "/ketones", priority: 0.6, changeFrequency: 'monthly', search: { title: "ケトン体", sub: "Ketones", group: "しくみ" } },
    { path: "/legal", priority: 0.3, changeFrequency: 'monthly' },
    { path: "/library", priority: 0.8, changeFrequency: 'weekly' },
    { path: "/library/map", priority: 0.5, changeFrequency: 'monthly' },
    { path: "/medical-roles", priority: 0.7, changeFrequency: 'monthly' },
    { path: "/mental-health", priority: 0.6, changeFrequency: 'monthly', search: { title: "心の現代病", sub: "うつ・不安・燃え尽きを体からとらえる", group: "しくみ" } },
    { path: "/menopause", priority: 0.7, changeFrequency: 'monthly', search: { title: "更年期・更年期移行期", sub: "ホルモンの揺らぎと40代の心身", group: "ホルモン" } },
    { path: "/male-menopause", priority: 0.7, changeFrequency: 'monthly', search: { title: "男性更年期（LOH症候群）", sub: "テストステロンと40代の心身", group: "ホルモン" } },
    { path: "/metabolic-syndrome", priority: 0.7, changeFrequency: 'monthly', search: { title: "メタボリックシンドローム", sub: "腹囲・血圧・血糖・脂質のつながり", group: "しくみ" } },
    { path: "/methylation", priority: 0.6, changeFrequency: 'monthly', search: { title: "メチレーション", sub: "Methylation", group: "しくみ" } },
    { path: "/microbiome", priority: 0.6, changeFrequency: 'monthly', search: { title: "腸内フローラとプレ・プロバイオティクス", sub: "善玉菌の育て方", group: "しくみ" } },
    { path: "/migraine", priority: 0.6, changeFrequency: 'monthly', search: { title: "片頭痛と体", sub: "引き金・栄養・受診の目安", group: "しくみ" } },
    { path: "/mindfulness", priority: 0.6, changeFrequency: 'monthly', search: { title: "マインドフルネス・呼吸", sub: "Breath / Mindfulness", group: "心とからだ" } },
    { path: "/mission", priority: 0.7, changeFrequency: 'monthly', search: { title: "なぜ、未病予防か", sub: "Our Mission", group: "考え方" } },
    { path: "/mitochondria", priority: 0.8, changeFrequency: 'monthly', search: { title: "ミトコンドリア", sub: "Mitochondria", group: "しくみ" } },
    { path: "/modern-diseases", priority: 0.6, changeFrequency: 'monthly', search: { title: "現代病とは", sub: "なぜ便利な暮らしが人を病気にするのか", group: "しくみ" } },
    { path: "/molecular-nutrition", priority: 0.8, changeFrequency: 'monthly', search: { title: "分子栄養学とは", sub: "Molecular Nutrition", group: "考え方" } },
    { path: "/mood-nutrition", priority: 0.6, changeFrequency: 'monthly', search: { title: "気分と栄養", sub: "Mood & Food", group: "心とからだ" } },
    { path: "/mycotoxins", priority: 0.6, changeFrequency: 'monthly', search: { title: "カビ毒と食の安全", sub: "マイコトキシン（アフラトキシン等）", group: "しくみ" } },
    { path: "/neuroinflammation", priority: 0.6, changeFrequency: 'monthly', search: { title: "神経炎症とは", sub: "IL-6・サイトカインが脳と心に及ぶとき", group: "しくみ" } },
    { path: "/newsletter", priority: 0.6, changeFrequency: 'monthly', search: { title: "Mitoflow40 レター", sub: "ニュースレター登録（無料・いつでも解除）", group: "サービス" } },
    { path: "/newsletter/archive", priority: 0.5, changeFrequency: 'weekly' },
    { path: "/nutrient-density", priority: 0.6, changeFrequency: 'monthly', search: { title: "食べ物の栄養価の変化", sub: "下がる野菜・上がるきのこ（希釈効果・UV照射）", group: "しくみ" } },
    { path: "/nutrients", priority: 0.7, changeFrequency: 'monthly' },
    { path: "/nutrition-history", priority: 0.7, changeFrequency: 'monthly', search: { title: "栄養学の歴史", sub: "カロリーからビタミン、そして細胞へ", group: "考え方" } },
    { path: "/nutrition-literacy", priority: 0.8, changeFrequency: 'monthly', search: { title: "学ぶと、何が変わる？", sub: "生化学・栄養学を知る価値 / Nutrition Literacy", group: "考え方" } },
    { path: "/organs", priority: 0.7, changeFrequency: 'monthly' },
    { path: "/oxidative-stress", priority: 0.6, changeFrequency: 'monthly', search: { title: "酸化ストレス（さびる）", sub: "Oxidative Stress", group: "しくみ" } },
    { path: "/periodontal-disease", priority: 0.6, changeFrequency: 'monthly', search: { title: "歯周病とは", sub: "口の中の慢性炎症が、全身に広がる理由", group: "しくみ" } },
    // ライブラリ配下ではなく単体ページ。横断検索（search）には載せず、sitemap のみ。
    { path: "/plans", priority: 0.8, changeFrequency: 'monthly', search: { title: "料金プラン・お申し込み", sub: "血液検査解析プラン／ミトフロープラン", group: "サービス" } },
    { path: "/podcast", priority: 0.7, changeFrequency: 'weekly' },
    { path: "/precision-nutrition", priority: 0.8, changeFrequency: 'monthly', search: { title: "精密栄養学とは", sub: "Precision Nutrition", group: "考え方" } },
    { path: "/privacy", priority: 0.3, changeFrequency: 'monthly' },
    { path: "/psychedelics-research", priority: 0.4, changeFrequency: 'monthly', search: { title: "サイケデリック研究の潮流", sub: "海外の研究動向（中立解説）", group: "考え方" } },
    { path: "/reduce-toxins", priority: 0.6, changeFrequency: 'monthly', search: { title: "有害物質を減らす暮らし", sub: "農薬・水銀・マイクロプラスチック", group: "しくみ" } },
    { path: "/references", priority: 0.5, changeFrequency: 'monthly', search: { title: "参照文献・出典", sub: "References", group: "考え方" } },
    { path: "/rice", priority: 0.6, changeFrequency: 'monthly', search: { title: "白米・玄米の真実", sub: "血糖・栄養・フィチン酸・ヒ素", group: "食べ物" } },
    { path: "/sample", priority: 0.7, changeFrequency: 'monthly' },
    { path: "/sarcopenia", priority: 0.6, changeFrequency: 'monthly', search: { title: "サルコペニア・フレイル", sub: "40代から始まる筋肉の減少・代謝と血糖", group: "しくみ" } },
    { path: "/sleep", priority: 0.6, changeFrequency: 'monthly', search: { title: "睡眠", sub: "Sleep", group: "生活習慣" } },
    { path: "/smell", priority: 0.6, changeFrequency: 'monthly', search: { title: "匂いと健康", sub: "記憶・感情・脳とのつながりと、アロマの見極め", group: "心とからだ" } },
    { path: "/sound", priority: 0.6, changeFrequency: 'monthly', search: { title: "音と健康", sub: "α波・振動・音楽療法と周波数ヒーリング", group: "心とからだ" } },
    { path: "/spirituality", priority: 0.6, changeFrequency: 'monthly', search: { title: "スピリチュアリティと体", sub: "心身相関の科学 / 祈り・瞑想・つながり", group: "心とからだ" } },
    { path: "/stimulants", priority: 0.6, changeFrequency: 'monthly', search: { title: "嗜好品と体", sub: "アルコール・タバコ・カフェイン", group: "生活習慣" } },
    { path: "/stress", priority: 0.6, changeFrequency: 'monthly', search: { title: "ストレスとは", sub: "Stress", group: "心とからだ" } },
    { path: "/sunlight", priority: 0.6, changeFrequency: 'monthly', search: { title: "日光と健康", sub: "体内時計・ビタミンD・紫外線とのつき合い方", group: "生活習慣" } },
    { path: "/supplements", priority: 0.7, changeFrequency: 'monthly', search: { title: "サプリメント", sub: "Supplements", group: "生活習慣" } },
    { path: "/symptoms", priority: 0.8, changeFrequency: 'monthly' },
    { path: "/tca-cycle", priority: 0.6, changeFrequency: 'monthly', search: { title: "TCA回路（クエン酸回路）", sub: "TCA Cycle", group: "しくみ" } },
    { path: "/terms", priority: 0.3, changeFrequency: 'monthly' },
    { path: "/thoughts", priority: 0.7, changeFrequency: 'monthly' },
    { path: "/water", priority: 0.6, changeFrequency: 'monthly', search: { title: "水と健康", sub: "必要量・脱水・「機能水」を中立に", group: "生活習慣" } },
    { path: "/wearables", priority: 0.6, changeFrequency: 'monthly', search: { title: "ウェアラブル活用", sub: "Wearables", group: "生活習慣" } },
    { path: "/wheat", priority: 0.6, changeFrequency: 'monthly', search: { title: "小麦と健康", sub: "血糖・グルテン・精製と、上手なつき合い方", group: "食べ物" } },
];
